version: "3.7"
services: 
    node: 
        build: 
            context: "."
            dockerfile: Dockerfile
        container_name: ts-node
        env_file: .env
        environment: 
            - "MYSQL_CONNECTION_LIMIT=${MYSQL_CONNECTION_LIMIT}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_HOST=${MYSQL_HOST}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_PORT=${MYSQL_PORT}"
            - "MYSQL_USER=${MYSQL_USER}"
        networks: 
            backend:
                ipv4_address: "172.18.0.3"
        ports: 
            - "3200:3000"
        restart: always

networks:
  backend:
    name: backend
    # driver: overlay
    # ipam:
    #  config:
    #    - subnet: "172.18.0.0/16"